# Description of the physical system
We have two molecules ($q_1$ and $q_2$) that each have a ground and excited state, $|g\rangle, |e\rangle$.
Each molecule also has one vibrational mode ($v_1$ and $v_2$) with occupation states $|0\rangle, |1\rangle$.  The molecules can be coupled to a single photonic (cavity) mode, $c$ with occupation states $|0\rangle, |1\rangle$.  One important note which is counter-intuitive is that we must give the cavity vibrational states and coupling as well.  In the case that one (or more) qubits are strongly coupled to the cavity, then we end up with polariton states that have different vibronic coupling than the bare molecular states.  The vibronic coupling exists in the tensor product space between the qubit, the cavity, and the vibrations.

We are going to work in an uncoupled basis with states

$$ |q_1, c, q_2, v_1, v_c, v_2\rangle $$

We will consider evolving the initial state

$|\psi(t=0)\rangle = |e, 0, g, 0, 0, 0\rangle$ subject to coupling between $q_1$ and $c$ with vibronic coupling that
we parameterize from a QED-CI calculation.  The second qubit will not be coupled to the cavity, but will have vibronic coupling that we parameterize from a CI calculation.

In the uncoupled basis, we can write the Hamiltonian as follows:

\begin{align}
\hat{H} = \hat{H}_{q_1} + \hat{H}_{c} + \hat{H}_{q_1-c} + \hat{H}_{q_1-c-v_1-v_c} + \hat{H}_{q_2} + \hat{H}_{v_2} + \hat{H}_{q_2-v_2} 
\end{align}

with the Hamiltonian terms that act only on a single subspace given by
\begin{align}
 \hat{H}_{q_1} &= \mathcal{H}_{q_1} \otimes \mathcal{I}_c \otimes \mathcal{I}_{q_2} \otimes \mathcal{I}_{v_1} \otimes \mathcal{I}_{v_c} \otimes \mathcal{I}_{v_2} \\
  \hat{H}_{c} &= \mathcal{I}_{q_1} \otimes \mathcal{H}_c \otimes \mathcal{I}_{q_2} \otimes \mathcal{I}_{v_1} \otimes \mathcal{I}_{v_c} \otimes \mathcal{I}_{v_2} \\
\hat{H}_{q_2} &= \mathcal{I}_{q_1} \otimes \mathcal{I}_c \otimes \mathcal{H}_{q_2} \otimes \mathcal{I}_{v_1} \otimes \mathcal{I}_{v_c} \otimes \mathcal{I}_{v_2} \\
\hat{H}_{v_2} &= \mathcal{I}_{q_1} \otimes \mathcal{I}_c \otimes \mathcal{I}_{q_2} \otimes \mathcal{I}_{v_1} \otimes \mathcal{I}_{v_c} \otimes \mathcal{H}_{v_2} \\
 \end{align}

 with 
\begin{align} 
\mathcal{H}_{q_1} &= \mathcal{H}_{q_2} = -\frac{\omega_q}{2} \sigma_z \\
\mathcal{H}_{c} &= \omega_c b^{\dagger} b \\
\mathcal{H}_{v_2} &= \omega_{v2} b^{\dagger} b.
\end{align}
The qubit-cavity coupling is given by the Pauli-Fierz Hamiltonian truncated to 2 levels for the qubit and 2 photonic Fock states for the cavity:
\begin{align}
\hat{H}_{q_1-c} &= -\sqrt{ \frac{\omega_c}{2}} \mathcal{d} \otimes \left(\mathcal{b}^{\dagger} + \mathcal{ b} \right) \otimes \mathcal{I}_{q_2}  \otimes \mathcal{I}_{v_1} \otimes \mathcal{I}_{v_c} \otimes \mathcal{I}_{v_2} \\
                &+ \frac{1}{2} \mathcal{d}^2 \otimes \mathcal{I}_{c} \otimes \mathcal{I}_{q_2}  \otimes \mathcal{I}_{v_1} \otimes \mathcal{I}_{v_c} \otimes \mathcal{I}_{v_2}
\end{align}
where $\mathcal{d} = \lambda \cdot \left(\mu_{gg} \sigma^- \sigma^+ + \mu_{ee} \sigma^+ \sigma^-  + \mu_{eg} \sigma_x \right)$
and the vibronic coupling for qubit 2 is given by the Holstein term
\begin{equation}
\hat{H}_{q_2-v_2} = \sqrt{S} \omega_{v_2} \mathcal{I}_{q_1} \otimes \mathcal{I}_{c}  \otimes \mathcal{\sigma}^+ \mathcal{\sigma}^- \otimes 
\mathcal{I}_{v_1} \otimes \mathcal{I}_{v_c} \otimes
\left(\mathcal{b}^{\dagger} + \mathcal{b}\right) 
\end{equation}
where $S$ is the Huang-Rhys factor associated with the transition for qubit 2 and $\omega_{v_2} = \frac{\omega + \omega'}{2}$ is the average of the vibrational frequency on the ground and excited state of qubit 2.

Importantly, we do not know a simple form for $\hat{H}_{q_1-c-v_1-v_c}$.  However, we can parameterize a polaritonic-vibronic Hamiltonian term from QED-CI calculations as follows.  

**Note 1** Each polaritonic state from a QED-CI calculation ($pol1 \rightarrow$ lowest energy eigenstate, $pol2 \rightarrow$ lower polariton state, $pol3 \rightarrow$ upper-polariton state, $pol4 \rightarrow$ highest energy eigenstate) will have an equilibrium geometry and fundamental vibrational frequency.  We can also identify Huang-Rhys factors for the transitions between each polariton state.  With this information together, we can write a Hamiltonian that contains the polaritonic vibrational states and their couplings as follows:

$$ \hat{H}_{pol-vib} = \sum_{i=1}^4  \omega_i |i\rangle \langle i| \otimes \mathcal{I}_{q_2} \otimes \mathcal{b}^{\dagger} \mathcal{b} \otimes \mathcal{I}_{v_2} + \sum_{i \neq j}^4 \sqrt{S_{ij}} \frac{\omega_i + \omega_j}{2} |i\rangle \langle j| \otimes \mathcal{I}_{q_2} \otimes \left( \mathcal{b}^{\dagger} + \mathcal{b} \right) \otimes \mathcal{I}_{v_2} $$

where the projection operator $|i\rangle\langle j|$ is defined in terms of polariton states $i$ and $j$.

We can define a transformation matrix from the uncoupled basis to the polariton basis by diagonalizing the PF term:

$$ \hat{H}_{pol} = \mathcal{U}^{\dagger} \hat{H}_{q_1-c} \mathcal{U} $$

such that we can define $\hat{H}_{q_1-c-v_1-v_c}$ as a related transformation on $\hat{H}_{pol-vib}$:

$$ \hat{H}_{q_1-c-v_1-v_c} = \mathcal{U} \hat{H}_{pol-vib} \mathcal{U}^{\dagger} $$

**Note 2** We build $\hat{H}_{q_1-c}$ utilizing the same $\lambda$, $\omega_c$ we used for the QED-CI calculations, and we parameterize $mathcal{d}$ and $\omega_q$ from CI calculations on the bare molecular system.  We diagonalize this matrix to generate $\mathcal{U}$.

**Note 3** All terms besides $\hat{H}_{q_1-c-v_1-v_c}$ can be build directly in the uncoupled basis using $\lambda$, $\omega_c$ from the QED-CI calculation, $\omega_q$, $\omega$, $\omega'$, and $S$ from a CI calculation on the qubit system.  $\hat{H}_{pol-vib}$ can be build directly from the QED-CI calculation, and then transformed to build $\hat{H}_{q_1-c-v_1-v_c}$.

**Note 4** We propagate with the total Hamiltonian in the uncoupled basis.


Some details about MgH+ coupled to a cavity at 

In [ ]:
from htc_numpy import HTC_Numpy
import numpy as np

params = {
    # --- Hilbert space truncations ---
    "dim_cavity": 2,             # truncate cavity to 2 photon levels
    "dim_vib": 2,                # truncate each vibrational mode to 2 levels
    "n_qubits": 2,               # number of qubits
    "n_vib_per_qubit": 1,        # each qubit has 1 vibrational mode

    # --- Uncoupled basis parameters ---
    "lambda_value" : 0.1,           #  fundamental cavity coupling strength λ
    "freq_cavity": 0.135973,        # ω_cavity for MgH+
    "freq_qubit": 1.0,              # ω_qubit
    "freq_vib_qubit": 0.1,          # ω_v (qubit vibrational mode)
    "coupling_qubit_vib": 0.01,     # Huang–Rhys factor λ (qubit–vibration coupling)
    "qubit_dipole_values": [1.0, 1.0, 1.0], # [μ_gg, μ_eg, μ_ee] dipole matrix elements

    # --- Polaritonic basis parameters ---
    "polariton_energies": [-0.16771931,  0.74784896,  1.34518339,  4.07468696],    # E_pol states
    "polariton_vib_frequencies": [0.1, 0.1, 0.1, 0.1],  # vib freq per polariton
    "polariton_vib_couplings": [0.01, 0.01, 0.01],     # λ per polariton surface
}

### some parameters for MgH+ at r = 1.65 Angstroms

mu_gg = -2.753928108005

   0 ->    0      -0.000000000000      -0.000000000000      -2.753928108005
   0 ->    1      -0.000000000000      -0.000000000000       0.000000000001
   0 ->    2       0.000000000001       0.000000000000      -0.784657504495
   0 ->    3      -0.000000000000      -0.000000000000       1.460663962807
   0 ->    4      -0.000000000107       0.000000001875      -0.000000000000
   0 ->    5       0.000000496820      -0.000008720599       0.000000000000
   1 ->    1      -0.000000000000       0.000000000000      -0.374872606348
   1 ->    2      -0.000000000000       0.000000000000      -0.000000000001
   1 ->    3      -0.000000000000      -0.000000000000      -0.000000000001
   1 ->    4      -1.652969115801      -0.094527784842       0.000000000000
   1 ->    5      -0.094527784463       1.652969109120       0.000000000000
   2 ->    2      -0.000000000000       0.000000000000      -2.316729450526
   2 ->    3       0.000000000000       0.000000000000      -0.945457923713
   2 ->    4       0.000000000040      -0.000000000698      -0.000000000000
   2 ->    5      -0.000000185031       0.000003247821       0.000000000000
   3 ->    3      -0.000000000000      -0.000000000000      -1.218679897112

# Example: 1 cavity, 2 qubits, 2 vib modes, truncation=2
model = HTC_Numpy(params)


np.set_printoptions(threshold=np.inf)


Total Hilbert space dimension: 32
cavity coupling λ: 1.0, qubit-vib λ: 0.01


In [15]:
# bosonic operators for the cavity
a = model.annihilation(model.dim_cavity)
a_dag = model.creation(model.dim_cavity)

# identity for cavity mode
I_cav = np.eye(model.dim_cavity)
# identity for qubit
I_qubit = np.eye(model.dim_qubit)

# d for the Pauli-Fierz Hamiltonian
d = model.lambda_value * model.qubit_dipole_matrix

# Pauli-Fierz Hamiltonian - might want to re-order the basis so cavity is first
H_PF = -0.5 * model.freq_qubit * np.kron(I_cav, model.sigma_z()) 
H_PF += model.freq_cavity * np.kron(a_dag @ a, I_qubit,)
H_PF += - np.sqrt(model.freq_cavity / 2) * np.kron((a_dag + a), d)
H_PF += 0.5 * np.kron(I_cav, (d @ d)) 
print("Pauli-Fierz Hamiltonian:\n", H_PF)

vals, vecs = np.linalg.eigh(H_PF)
print(vals)

# this is the transformation from 
init_state_pol = vecs[2,:]
print(init_state_pol)

# initial_state in uncoupled basis
init_rho_uncoupled = model.bu


Pauli-Fierz Hamiltonian:
 [[ 0.5         1.         -0.70710678 -0.70710678]
 [ 1.          1.5        -0.70710678 -0.70710678]
 [-0.70710678 -0.70710678  1.5         1.        ]
 [-0.70710678 -0.70710678  1.          2.5       ]]
[-0.16771931  0.74784896  1.34518339  4.07468696]
[0.15170869 0.85528118 0.12616059 0.47912637]


Build Polariton Hamiltonian with the following form:

$$ H = H_{pol} \otimes \mathcal{I}_2 + H_{pol-vib} + H_{pol_vib_coup} $$

where 

$$ H_{pol} = \sum_{i=1}^4 \epsilon_i |i\rangle \langle i| $$

$$ H_{pol-vib} = \sum_{i=1}^4 \omega_i |i\rangle \langle i| \otimes \left( \hat{b}^{\dagger} \hat{b} \right)$$

$$ H_{pol-vib-coup} = \sum_{i\neq j}^4 \lambda_{ij} \frac{\omega_i + \omega_j}{2} |i\rangle \langle i| \otimes \left( \hat{b}^{\dagger} + \hat{b} \right)$$

Here these quantities will come from a QED-CI calculation of some sort!

In [6]:
H_pol = model.build_polariton_hamiltonian()
print("Polaritonic Hamiltonian:\n", H_pol)

H_polvib = model.build_polariton_vibrational_hamiltonian()
print("Polaritonic + Vibrational Hamiltonian:\n", H_polvib)

H_polvib_coupling = model.build_polariton_vib_coupling()
print("Polaritonic + Vibrational + Coupling Hamiltonian:\n", H_polvib_coupling)

H = np.kron(H_pol, np.eye(model.dim_vib)) + H_polvib + H_polvib_coupling
print("Total Hamiltonian:\n", H)

Polaritonic Hamiltonian:
 [[-0.16771931  0.          0.          0.        ]
 [ 0.          0.74784896  0.          0.        ]
 [ 0.          0.          1.34518339  0.        ]
 [ 0.          0.          0.          4.07468696]]
Polaritonic + Vibrational Hamiltonian:
 [[0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.1 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.1 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.1 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.1]]
Polaritonic + Vibrational + Coupling Hamiltonian:
 [[0.   0.   0.   0.01 0.   0.01 0.   0.01]
 [0.   0.   0.01 0.   0.01 0.   0.01 0.  ]
 [0.   0.01 0.   0.   0.   0.   0.   0.  ]
 [0.01 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.01 0.   0.   0.   0.   0.   0.  ]
 [0.01 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.01 0.   0.   0.   0.   0.   0.  ]
 [0.01 0.   0.   0.   0.   0.   0.   0.  ]]
Total Hamiltonian:
 [[-0.16771931  0.          0.   

We next want to build the Pauli-Fierz Hamiltonian that corresponds to $H_{pol}$ in the following way:

$$ \hat{U}^{\dagger} H_{\rm PF} \hat{U} = H_{pol} $$

with 

$$ H_{\rm PF} = -\frac{\omega}{2} \sigma_z \otimes \mathcal{I}_{2} + \omega \mathcal{I}_{2} \otimes \hat{a}^{\dagger} \hat{a} - \sqrt{\frac{\omega}{2}} \lambda \cdot \hat{\mu} \otimes \left(\hat{a}^{\dagger} + \hat{a}  \right) + \frac{1}{2} (\lambda \cdot \hat{\mu})^2 \otimes \mathcal{I}_2 $$

In [ ]:
# bosonic operators for the cavity
a = model.annihilation(model.dim_cavity)
a_dag = model.creation(model.dim_cavity)

# identity for cavity mode
I_cav = np.eye(model.dim_cavity)
# identity for qubit
I_qubit = np.eye(model.dim_qubit)

# d for the Pauli-Fierz Hamiltonian
d = model.lambda_value * model.qubit_dipole_matrix

# Pauli-Fierz Hamiltonian - might want to re-order the basis so cavity is first
H_PF = -0.5 * model.freq_qubit * np.kron(model.sigma_z(), I_cav) 
H_PF += model.freq_cavity * np.kron(I_qubit, a_dag @ a)
H_PF += - np.sqrt(model.freq_cavity / 2) * np.kron(d, (a_dag + a))
H_PF += 0.5 * np.kron((d @ d),  I_cav) 
print("Pauli-Fierz Hamiltonian:\n", H_PF)


Pauli-Fierz Hamiltonian:
 [[ 0.5        -0.70710678  1.         -0.70710678]
 [-0.70710678  1.5        -0.70710678  1.        ]
 [ 1.         -0.70710678  1.5        -0.70710678]
 [-0.70710678  1.         -0.70710678  2.5       ]]
DSE Term:
 [[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]]


Get the transformation matrix $$\hat{U}$$ by diagonalizing $H_{PF}$

In [6]:
eigs, U = np.linalg.eigh(H_PF)
print("Transformation matrix U:\n", U)

Transformation matrix U:
 [[ 0.8832374   0.08470876  0.29731553 -0.35258984]
 [ 0.15170869  0.85528118 -0.12616059  0.47912637]
 [-0.4395301   0.42648448  0.64909188 -0.45122501]
 [ 0.06074093 -0.28183242  0.68874285  0.66521749]]


In [ ]:
# build subspace operators

# bosonic operators
lowering = model.annihilation(model.dim_cavity)
raising = model.creation(model.dim_cavity)

# qubit operators
sigma_plus = model.sigma_plus()
sigma_minus = model.sigma_minus()
sigma_z = model.sigma_z()


# embed operators into full hilbert space
am = model.embed_operator(lowering, position=0)   # position=0 is cavity
ap = model.embed_operator(raising, position=0) 

bm1 = model.embed_operator(lowering, position=2) # position=2 is vib 1
bp1 = model.embed_operator(raising, position=2) 


sp1 = model.embed_operator(sigma_plus, position=1) # position=1 is qubit 1
sm1 = model.embed_operator(sigma_minus, position=1) 
sz1 = model.embed_operator(sigma_z, position=1)


AttributeError: 'HTC_Numpy' object has no attribute 'cav_dim'

\begin{equation}
H = \sum_i -\frac{\hbar \omega_i}{2} \sigma_{z,i} + \hbar \omega \hat{a}^\dagger \hat{a} +  \sum_i \hbar g_i ( \hat{a}  \sigma_{+,i} + \hat{a}^\dagger \sigma_{-,i} ) + \lambda \omega \sigma^+ \sigma^-( \hat{b}^{\dagger} + \hat{b} ) + \hbar \omega_v \hat{b}^{\dagger} \hat{b}
\end{equation}


In [ ]:
# build Hamiltonian where qubit 1 is coupled to the cavity
H1 = -model.omega_qubit / 2 * sz1   # qubit 1 energy 
H1 += model.omega_cav * ap @ am     # cavity energy
H1 += model.g * (am @ sp1 + ap @ sm1) # qubit 1 - cavity coupling

# get the polariton Hamiltonian
# diagonalize H1    
evals, evecs = np.linalg.eigh(H1)

H1 += model.omega_vib * bp1 @ bm1   # vib 1 energy
H1 += model.omega_vib * model.lambda_vib * sp1 @ sm1 @ (bp1 + bm1) # qubit 1 - vib 1 coupling


# diagonalize

In [ ]:
N_state = 8
# diagonalize H1
eigenvalues_1, polariton_1 = np.linalg.eigh(H1)

# express H1 in polariton basis
Hpol1 = polariton_1.T @ H1 @ polariton_1

# compute expectation value of state |0,e,0,g,0> in uncoupled basis
psi = model.basis_state(N_state)
#print(psi)

E_exp_uncoupled = psi.T @ H1 @ psi

psi_pol = polariton_1[N_state,:].reshape(32,1)
#print(psi_pol)
E_exp_pol = psi_pol.T @ Hpol1 @ psi_pol

print(E_exp_uncoupled)
print(E_exp_pol)
#print(F"Expectation value in uncoupled basis is {E_exp_uncoupled:12.10f}")
#print(F"Expectation value in polariton basis is {E_exp_pol:12.10f}")




In [ ]:
#target_basis_state = model.labels

model.represent_basis_in_eigenbasis(model.labels, polariton_1, energies=eigenvalues_1)

In [ ]:
# Get a basis vector
psi = model.basis_state(8)
print("Basis[8] =", model.labels[8], psi.T)

rho_init =  psi @ psi.T


In [ ]:
n_time_1 = np.pi / (4 * model.g)
n_time_2 = np.pi / (2 * model.g)

print(f"n_time_1 = {np.floor(n_time_1)}")
print(f"n_time_2 = {np.floor(n_time_2)}")




In [ ]:


dt = 0.01

n_time = int(40 / dt) # make sure we get to 40 a.u. of time

# arrays to store the populations at each time-step
pops_uncoupled = np.zeros((n_time,rho_init.shape[0]))

t = []


for i in range(n_time):
    if i * dt<n_time_1:
        # evolve in uncoupled basis
        rho_new = model.rk4_step(H1, rho_init, dt, hbar=1.0)

    elif i * dt < n_time_1 + n_time_2:
        rho_new = model.rk4_step(H2, rho_init, dt, hbar=1)

    else: 
        rho_new = model.rk4_step(H_un, rho_init, dt, hbar=1.0)


    t.append(i * dt)
    for k in range(rho_init.shape[0]):
        # store all populations
        pops_uncoupled[i,k] = np.real(rho_new[k,k])


    # copy updated rhos in each basis to the rho_init and rho_pol_init for next step
    rho_init = np.copy(rho_new)


In [ ]:
print(pops_uncoupled)

In [ ]:
from matplotlib import pyplot as plt
plt.plot(t, pops_uncoupled[:,8], label="$p_{99}$ uncoupled")
plt.plot(t, pops_uncoupled[:,16], label="$p_{1616}$ uncoupled")
plt.plot(t, pops_uncoupled[:,2], label="$p_{22}$ uncoupled")
plt.grid()
#plt.xlim(10,20)
plt.legend()
plt.show()